'use client';

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { TRADE_ESTIMATORS, getEstimatorByTrade } from '@/lib/material-estimator';
import type { PriceTier, EstimateResult } from '@/lib/materials-database';
import { getMaterialsByTrade } from '@/lib/materials-database';
import {
  Calculator,
  Paintbrush,
  Wrench,
  Zap,
  TreePine,
  Layers,
  Hammer,
  ArrowLeft,
  ArrowRight,
  DollarSign,
  Package,
  Clock,
  CheckCircle,
  ShoppingCart,
  FileText,
  ChevronDown,
  ChevronUp,
  Home,
  Fence,
  Square,
  Droplets,
  Waves,
  Thermometer,
  Sun,
  DoorOpen,
  Printer,
  Smartphone,
  Mail,
  Copy,
} from 'lucide-react';

const TRADE_ICONS: Record<string, typeof Calculator> = {
  Paintbrush, Wrench, Zap, TreePine, Layers, Hammer, Home, Fence, Square, Droplets, Waves, Thermometer, Sun, DoorOpen,
};

const TIER_LABELS: Record<PriceTier, { label: string; description: string; color: string }> = {
  economy: { label: 'Good', description: 'Budget-friendly, gets the job done', color: 'border-green-300 bg-green-50' },
  standard: { label: 'Better', description: 'Most popular, great value', color: 'border-blue-300 bg-blue-50' },
  premium: { label: 'Best', description: 'Top brands, longest lasting', color: 'border-purple-300 bg-purple-50' },
};

export default function EstimatorPage() {
  const [selectedTrade, setSelectedTrade] = useState<string | null>(null);
  const [answers, setAnswers] = useState<Record<string, unknown>>({});
  const [selectedTier, setSelectedTier] = useState<PriceTier>('standard');
  const [result, setResult] = useState<EstimateResult | null>(null);
  const [step, setStep] = useState<'trade' | 'specs' | 'results'>('trade');
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());
  const [copied, setCopied] = useState(false);

  const estimator = selectedTrade ? getEstimatorByTrade(selectedTrade) : null;

  // Initialize defaults when trade is selected
  const initializeAnswers = (trade: string) => {
    const est = getEstimatorByTrade(trade);
    if (!est) return;
    const defaults: Record<string, unknown> = {};
    for (const q of est.questions) {
      if (q.defaultValue !== undefined) {
        defaults[q.id] = q.defaultValue;
      }
    }
    setAnswers(defaults);
    setSelectedTrade(trade);
    setResult(null);
    setStep('specs');
  };

  // Build a plain-text shopping list from the estimate
  const buildShoppingList = (): string => {
    if (!result || !estimator) return '';
    const lines: string[] = [];
    lines.push(`SHOPPING LIST — ${estimator.name}`);
    lines.push(`Tier: ${TIER_LABELS[selectedTier].label}`);
    lines.push(`Generated by ToolTime Pro`);
    lines.push('');
    lines.push('─'.repeat(40));

    // Group items by category
    const grouped: Record<string, typeof result.items> = {};
    for (const item of result.items) {
      const material = getMaterialsByTrade(estimator.trade).find(m => m.id === item.materialId);
      const cat = material?.category || 'Other';
      if (!grouped[cat]) grouped[cat] = [];
      grouped[cat].push(item);
    }

    for (const [category, items] of Object.entries(grouped)) {
      lines.push(`\n${category.toUpperCase()}`);
      for (const item of items) {
        lines.push(`  □ ${item.quantity} ${item.unit} — ${item.name}`);
        lines.push(`    Brand: ${item.brand} | $${item.unitPrice.toFixed(2)} ea = $${item.total.toFixed(2)}`);
      }
    }

    lines.push('');
    lines.push('─'.repeat(40));
    lines.push(`MATERIAL TOTAL: $${result.materialTotal.toFixed(2)}`);
    lines.push(`LABOR ESTIMATE: $${result.laborEstimate.toFixed(2)} (${result.laborHours}h)`);
    lines.push(`GRAND TOTAL: $${result.grandTotal.toFixed(2)}`);

    if (result.notes.length > 0) {
      lines.push('');
      lines.push('NOTES:');
      result.notes.forEach(n => lines.push(`  • ${n}`));
    }

    return lines.join('\n');
  };

  const handlePrint = () => {
    const list = buildShoppingList();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`<html><head><title>Shopping List — ${estimator?.name}</title><style>body{font-family:monospace;white-space:pre-wrap;padding:20px;font-size:14px;}@media print{body{font-size:12px;}}</style></head><body>${list}</body></html>`);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleCopyList = async () => {
    const list = buildShoppingList();
    try {
      await navigator.clipboard.writeText(list);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = list;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleTextToPhone = () => {
    const list = buildShoppingList();
    // Use SMS URI scheme — opens native messaging app
    const encoded = encodeURIComponent(list);
    window.open(`sms:?body=${encoded}`, '_self');
  };

  const handleEmailList = () => {
    const list = buildShoppingList();
    const subject = encodeURIComponent(`Shopping List — ${estimator?.name || 'Material Estimate'}`);
    const body = encodeURIComponent(list);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handleCalculate = () => {
    if (!estimator) return;
    const res = estimator.calculate(answers, selectedTier);
    setResult(res);
    setStep('results');
  };

  const shouldShowQuestion = (q: typeof estimator extends null ? never : NonNullable<typeof estimator>['questions'][0]) => {
    if (!q.showWhen) return true;
    return answers[q.showWhen.field] === q.showWhen.value ||
      String(answers[q.showWhen.field]) === String(q.showWhen.value);
  };

  // Group result items by category
  const groupedItems = useMemo(() => {
    if (!result) return {};
    const groups: Record<string, typeof result.items> = {};
    for (const item of result.items) {
      const category = item.name.includes('Paint') || item.name.includes('Primer') ? 'Paint & Primer' :
        item.name.includes('Tape') || item.name.includes('Drop') || item.name.includes('Roller') || item.name.includes('Brush') || item.name.includes('Tray') ? 'Supplies & Tools' :
        item.name.includes('Caulk') || item.name.includes('Spackle') || item.name.includes('Sand') ? 'Prep Materials' :
        'Materials';
      if (!groups[category]) groups[category] = [];
      groups[category].push(item);
    }
    return groups;
  }, [result]);

  const toggleCategory = (cat: string) => {
    setExpandedCategories(prev => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat); else next.add(cat);
      return next;
    });
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="bg-navy-gradient rounded-2xl p-8 text-white">
        <div className="flex items-center gap-4 mb-4">
          <div className="w-14 h-14 bg-gold-500 rounded-xl flex items-center justify-center">
            <Calculator className="w-8 h-8 text-navy-500" />
          </div>
          <div>
            <h1 className="text-2xl font-bold">Material Estimator</h1>
            <p className="text-white/70">Know Your Costs Before You Quote</p>
          </div>
        </div>
        <p className="text-white/80 max-w-2xl">
          Tell us about the job, and we&apos;ll calculate exactly what materials you need, how much they cost,
          and estimated labor — with Good / Better / Best pricing tiers. Add the estimate directly to a quote.
        </p>
      </div>

      {/* Step 1: Select Trade */}
      {step === 'trade' && (
        <div>
          <h2 className="text-lg font-semibold text-navy-500 mb-4">What type of work?</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {TRADE_ESTIMATORS.map(est => {
              const Icon = TRADE_ICONS[est.icon] || Calculator;
              return (
                <button
                  key={est.trade}
                  onClick={() => initializeAnswers(est.trade)}
                  className="card-hover text-left group"
                >
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-gold-100 rounded-lg flex items-center justify-center group-hover:bg-gold-500 transition-colors">
                      <Icon className="w-6 h-6 text-gold-600 group-hover:text-navy-500 transition-colors" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-navy-500 group-hover:text-gold-600 transition-colors">
                        {est.name}
                      </h3>
                      <p className="text-sm text-gray-500 mt-1">{est.description}</p>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Step 2: Job Specs */}
      {step === 'specs' && estimator && (
        <div className="card">
          <div className="flex items-center gap-3 mb-6">
            <button onClick={() => { setStep('trade'); setSelectedTrade(null); }} className="p-2 hover:bg-gray-100 rounded-lg">
              <ArrowLeft className="w-5 h-5 text-gray-500" />
            </button>
            <h2 className="text-lg font-semibold text-navy-500">{estimator.name} — Job Details</h2>
          </div>

          <div className="space-y-5">
            {estimator.questions.filter(shouldShowQuestion).map(q => (
              <div key={q.id + (q.showWhen?.field || '')}>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">
                  {q.label}
                  {q.required && <span className="text-red-500 ml-1">*</span>}
                </label>

                {q.type === 'number' && (
                  <div className="flex items-center gap-2">
                    <input
                      type="number"
                      min="0"
                      value={answers[q.id] as number || ''}
                      onChange={e => setAnswers(prev => ({ ...prev, [q.id]: e.target.value ? Number(e.target.value) : '' }))}
                      className="w-32 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 text-lg"
                    />
                    {q.unit && <span className="text-sm text-gray-500">{q.unit}</span>}
                  </div>
                )}

                {q.type === 'select' && (
                  <select
                    value={String(answers[q.id] || q.defaultValue || '')}
                    onChange={e => setAnswers(prev => ({ ...prev, [q.id]: e.target.value }))}
                    className="w-full px-3 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gold-500 focus:border-gold-500 text-sm"
                  >
                    {q.options?.map(opt => (
                      <option key={opt.value} value={opt.value}>{opt.label}</option>
                    ))}
                  </select>
                )}

                {q.type === 'checkbox' && (
                  <label className="flex items-center gap-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={answers[q.id] === true}
                      onChange={e => setAnswers(prev => ({ ...prev, [q.id]: e.target.checked }))}
                      className="w-5 h-5 text-gold-500 rounded border-gray-300 focus:ring-gold-500"
                    />
                    <span className="text-sm text-gray-600">{q.helpText || 'Yes'}</span>
                  </label>
                )}

                {q.helpText && q.type !== 'checkbox' && (
                  <p className="text-xs text-gray-400 mt-1">{q.helpText}</p>
                )}
              </div>
            ))}
          </div>

          {/* Tier Selection */}
          <div className="border-t mt-6 pt-6">
            <h3 className="text-sm font-medium text-gray-700 mb-3">Material quality tier</h3>
            <div className="grid grid-cols-3 gap-3">
              {(['economy', 'standard', 'premium'] as PriceTier[]).map(tier => {
                const info = TIER_LABELS[tier];
                const isSelected = selectedTier === tier;
                return (
                  <button
                    key={tier}
                    onClick={() => setSelectedTier(tier)}
                    className={`p-3 rounded-xl border-2 text-left transition-all ${
                      isSelected ? info.color + ' ring-2 ring-offset-1 ring-gold-400' : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <p className="font-semibold text-sm text-gray-900">{info.label}</p>
                    <p className="text-xs text-gray-500 mt-0.5">{info.description}</p>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="flex justify-end mt-6">
            <button onClick={handleCalculate} className="btn-primary flex items-center gap-2 text-lg px-8 py-3">
              <Calculator className="w-5 h-5" />
              Calculate Estimate
            </button>
          </div>
        </div>
      )}

      {/* Step 3: Results */}
      {step === 'results' && result && estimator && (
        <div className="space-y-6">
          <div className="flex items-center gap-3">
            <button onClick={() => setStep('specs')} className="p-2 hover:bg-gray-100 rounded-lg">
              <ArrowLeft className="w-5 h-5 text-gray-500" />
            </button>
            <h2 className="text-lg font-semibold text-navy-500">{estimator.name} Estimate</h2>
            <span className={`px-3 py-1 rounded-full text-xs font-medium ${
              selectedTier === 'economy' ? 'bg-green-100 text-green-700' :
              selectedTier === 'standard' ? 'bg-blue-100 text-blue-700' :
              'bg-purple-100 text-purple-700'
            }`}>
              {TIER_LABELS[selectedTier].label} Tier
            </span>
          </div>

          {/* Cost Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="card border-2 border-orange-100 text-center">
              <Package className="w-6 h-6 text-orange-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-orange-600">
                ${result.materialTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </p>
              <p className="text-sm text-gray-500">Materials</p>
            </div>
            <div className="card border-2 border-blue-100 text-center">
              <Clock className="w-6 h-6 text-blue-500 mx-auto mb-1" />
              <p className="text-2xl font-bold text-blue-600">
                ${result.laborEstimate.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </p>
              <p className="text-sm text-gray-500">Labor ({result.laborHours}h est.)</p>
            </div>
            <div className="card border-2 border-navy-100 text-center">
              <DollarSign className="w-6 h-6 text-navy-500 mx-auto mb-1" />
              <p className="text-3xl font-bold text-navy-500">
                ${result.grandTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </p>
              <p className="text-sm text-gray-500">Total Estimate</p>
            </div>
          </div>

          {/* Compare Tiers */}
          <div className="card bg-gray-50">
            <h3 className="font-medium text-gray-700 mb-3">Compare All Tiers</h3>
            <div className="grid grid-cols-3 gap-4 text-center">
              {(['economy', 'standard', 'premium'] as PriceTier[]).map(tier => {
                const tierResult = estimator.calculate(answers, tier);
                const info = TIER_LABELS[tier];
                const isActive = tier === selectedTier;
                return (
                  <button
                    key={tier}
                    onClick={() => {
                      setSelectedTier(tier);
                      setResult(estimator.calculate(answers, tier));
                    }}
                    className={`p-4 rounded-xl border-2 transition-all ${
                      isActive ? info.color + ' ring-2 ring-gold-400' : 'border-gray-200 bg-white hover:border-gray-300'
                    }`}
                  >
                    <p className="font-semibold text-sm">{info.label}</p>
                    <p className="text-xl font-bold text-navy-500 mt-1">
                      ${tierResult.grandTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                    </p>
                    <p className="text-xs text-gray-400">materials: ${tierResult.materialTotal.toFixed(2)}</p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Material List */}
          <div className="card">
            <h3 className="font-semibold text-navy-500 mb-4 flex items-center gap-2">
              <ShoppingCart className="w-5 h-5" />
              Material List ({result.items.length} items)
            </h3>

            {Object.entries(groupedItems).map(([category, items]) => (
              <div key={category} className="mb-4">
                <button
                  onClick={() => toggleCategory(category)}
                  className="flex items-center justify-between w-full py-2 text-left"
                >
                  <span className="font-medium text-gray-700 text-sm">{category}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-gray-500">
                      ${items.reduce((s, i) => s + i.total, 0).toFixed(2)}
                    </span>
                    {expandedCategories.has(category) ? (
                      <ChevronUp className="w-4 h-4 text-gray-400" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-gray-400" />
                    )}
                  </div>
                </button>

                {!expandedCategories.has(category) && (
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-left text-xs text-gray-400 border-b">
                          <th className="pb-1 pr-2">Item</th>
                          <th className="pb-1 pr-2">Brand</th>
                          <th className="pb-1 pr-2 text-right">Qty</th>
                          <th className="pb-1 pr-2 text-right">Unit Price</th>
                          <th className="pb-1 text-right">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        {items.map((item, idx) => (
                          <tr key={idx} className="border-b border-gray-100">
                            <td className="py-2 pr-2">
                              <p className="font-medium text-gray-800">{item.name}</p>
                              <p className="text-xs text-gray-400">{item.description}</p>
                            </td>
                            <td className="py-2 pr-2 text-xs text-gray-500">{item.brand}</td>
                            <td className="py-2 pr-2 text-right text-gray-700">{item.quantity} {item.unit}</td>
                            <td className="py-2 pr-2 text-right text-gray-500">${item.unitPrice.toFixed(2)}</td>
                            <td className="py-2 text-right font-medium text-gray-900">${item.total.toFixed(2)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            ))}

            <div className="border-t pt-3 flex justify-between items-center">
              <span className="font-semibold text-navy-500">Material Total</span>
              <span className="text-xl font-bold text-navy-500">
                ${result.materialTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </span>
            </div>
          </div>

          {/* Notes */}
          {result.notes.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4">
              <h3 className="font-medium text-yellow-800 text-sm mb-2">Notes</h3>
              <ul className="space-y-1">
                {result.notes.map((note, i) => (
                  <li key={i} className="text-sm text-yellow-700 flex items-start gap-2">
                    <CheckCircle className="w-4 h-4 text-yellow-500 flex-shrink-0 mt-0.5" />
                    {note}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Shopping List Export */}
          <div className="card">
            <h3 className="font-semibold text-navy-500 mb-4 flex items-center gap-2">
              <ShoppingCart className="w-5 h-5" />
              Export Shopping List
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <button onClick={handlePrint} className="flex flex-col items-center gap-2 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                <Printer className="w-6 h-6 text-navy-500" />
                <span className="text-sm font-medium text-gray-700">Print List</span>
              </button>
              <button onClick={handleTextToPhone} className="flex flex-col items-center gap-2 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                <Smartphone className="w-6 h-6 text-navy-500" />
                <span className="text-sm font-medium text-gray-700">Text to Phone</span>
              </button>
              <button onClick={handleEmailList} className="flex flex-col items-center gap-2 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                <Mail className="w-6 h-6 text-navy-500" />
                <span className="text-sm font-medium text-gray-700">Email List</span>
              </button>
              <button onClick={handleCopyList} className="flex flex-col items-center gap-2 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                {copied ? <CheckCircle className="w-6 h-6 text-green-500" /> : <Copy className="w-6 h-6 text-navy-500" />}
                <span className="text-sm font-medium text-gray-700">{copied ? 'Copied!' : 'Copy List'}</span>
              </button>
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3">
            <Link
              href={`/dashboard/smart-quote?materials=${encodeURIComponent(JSON.stringify(result.items.map(i => ({ description: `${i.name} (${i.brand})`, quantity: i.quantity, unit_price: i.unitPrice }))))}`}
              className="btn-primary flex items-center justify-center gap-2 flex-1"
            >
              <FileText className="w-4 h-4" />
              Add to Quote
            </Link>
            <button
              onClick={() => setStep('specs')}
              className="btn-outline flex items-center justify-center gap-2"
            >
              <ArrowLeft className="w-4 h-4" />
              Adjust Specs
            </button>
            <button
              onClick={() => { setStep('trade'); setSelectedTrade(null); setResult(null); }}
              className="btn-outline flex items-center justify-center gap-2"
            >
              New Estimate
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
